title: 范轶清的blog
description: "金玉游龙"
baseurl: /
#permalink: /:year/:month/:day/:title.html
#highlighter: rouge # 使用rouge作为语法高亮引擎
markdown: kramdown  # 使用kramdown作为markdown的转换器
kramdown:
  input: GFM
  hard_wrap: true
gems:
  - jemoji # 要站点支持Github表情，必须添加
twitter_username: fanyiqing333
github_username: jinyuyoulong

# Github Pages默认配置项，Jekyll的配置可以覆盖
# kramdown:
#   input: GFM
#   hard_wrap: false
# gems:
#   - jekyll-coffeescript
#   - jekyll-paginate

# Github Pages不可改变项，会覆盖Jekyll的配置
# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#  noscript: false
# kramdown:
#  math_engine: mathjax